### ISSUE TITLE
Error: NoSuchMethodError: The getter 'latitude' was called on null.

### ISSUE THREAD

**Issue by roy2904** [londonappbrewery/Clima-Flutter#10]
Hello Angela,
I am facing some unexpected error in this refactor challenge of clima app.
In the video tutorial there is no error in the console, but when in my case its showing NoSuchMethodError: The getter 'latitude' was called on null.
I am attaching 2 pictures, maybe that can help.
![1](https://user-images.githubusercontent.com/32846419/82451418-9827b880-9acb-11ea-85be-4f9e05ec1df9.png)
![2](https://user-images.githubusercontent.com/32846419/82451444-a1188a00-9acb-11ea-866f-1df7dc607228.png)

please help

**Comment by azinmapar** [comment]
I have the same issue, how did you solve it?
