### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by shivamkg0604** [londonappbrewery/Clima-Flutter#21]
I am geeting nosuchmethoderror.I have copied the code .
but getting this error.
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Builder:
The method '[]' was called on null.
Receiver: null
Tried calling: []("main")

The relevant error-causing widget was: 
  MaterialApp file:///C:/Users/shiva/AndroidStudioProjects/Clima-Flutter/lib/main.dart:9:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      _LocationScreenState.update.<anonymous closure> (package:clima/screens/location_screen.dart:26:25)
#2      State.setState (package:flutter/src/widgets/framework.dart:1267:30)
#3      _LocationScreenState.update (package:clima/screens/location_screen.dart:25:5)
#4      _LocationScreenState.initState (package:clima/screens/location_screen.dart:21:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
E/UIFirst (23085): failed to open /proc/23085/stuck_info, No such file or directory
Lost connection to device.
![error](https://user-images.githubusercontent.com/82898016/115433719-7c6dea80-a225-11eb-9c62-1b03474dcd4d.jpg)

**Comment by azinmapar** [comment]
How did you solve it?? I have the same issue
